[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "projectmaster"
authors = [{name = "SETAP5D", email = "SETAP5D@setap"}]
dynamic = ["version", "description"]
